[theme]
base="dark"

# Text & primary highlight
textColor = "#e2e8f0"           # light text
primaryColor = "#14347C"        # Mongolbank primary blue

# Backgrounds
backgroundColor = "#0B2554"      # main app background
secondaryBackgroundColor = "#0F2F6B"  # sidebar background

# Widgets
showWidgetBorder = true
borderColor = "#314158"


# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Fonts
font="'PT Sans', sans-serif"
baseFontWeight=400
baseFontSize=14
headingFont="'PT Sans', sans-serif"
headingFontWeights=[400,700,400,400,400,400]
headingFontSizes=["2.5rem","1.5rem","1rem"]
