[theme]
base="dark"

# Text & primary highlight
textColor = "#e2e8f0"           
primaryColor = "#14347C"        # Mongolbank blue

# Backgrounds
backgroundColor = "#0B2554"      # Main (одоогийнх)
secondaryBackgroundColor = "#132F5E"  # ✅ ШИНЭ: бага зэрэг цайвар

# Widgets
showWidgetBorder = true
borderColor = "#14347C"          # ✅ ШИНЭ: банкны өнгө

# Dataframes
dataframeHeaderBackgroundColor = "#0F2953"

# Fonts
font="'PT Sans', sans-serif"
baseFontWeight=400
baseFontSize=14
headingFont="'PT Sans', sans-serif"
headingFontWeights=[400,700,400,400,400,400]
headingFontSizes=["2.5rem","1.5rem","1rem"]
