[theme]
base = "dark"

# Text
textColor = "#e5e7eb"

# ðŸ”µ Mongolbank main navy
backgroundColor = "#2E384D"

# ðŸ”µ Darker container background
secondaryBackgroundColor = "#1F2937"

# ðŸ”µ Accent blue (KPI, active, highlights)
primaryColor = "#3B82F6"

# Widgets
showWidgetBorder = true
borderColor = "#334155"

# Dataframes
dataframeHeaderBackgroundColor = "#2E384D"

# Font
font = "Space Grotesk"
baseFontWeight = 400
baseFontSize = 14


# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]
